### PR TITLE
Issue #469 is fixed (When run on Windows a lot of tests fail with the error: [Errno 13] Permission denied)

### PR DESCRIPTION
**Pull request by Ev2geny**
**Pull request**
This fixes issue
When run on Windows a lot of tests fail with the error: [Errno 13] Permission denied https://github.com/pdfminer/pdfminer.six/issues/469

Both detailed problem analysis as well as the solution implemented are described in https://github.com/pdfminer/pdfminer.six/issues/469

**How Has This Been Tested?**
I ran tests in Windows 10 environment and they all pass now

**Checklist**

- [x] I have added tests that prove my fix is effective or that my feature 
  works
- [x] I have added docstrings to newly created methods and classes - n/a
- [ ] I have optimized the code at least one time after creating the initial 
  version - 
- [x] I have updated the [README.md](../README.md) or I am verified that this
  is not necessary
- [x] I have updated the [readthedocs](../docs/source) documentation or I 
  verified that this is not necessary
- [x] I have added a consice human-readable description of the change to 
  [CHANGELOG.md](../CHANGELOG.md)

### CODE REVIEW

**Comment by pietermarsman** [comment]
Hi @Ev2geny, good catch! I've left a comment on the issue with some comments on the proposed solution. Could you change the PR to reflect that? 

What I'm suggesting is to create a new context manager `TemporaryFilePath()` that returns a temporary file path (without creating it) and to delete it after it is used. 

If you don't know context managers (that's what the `with` thing is) you could read [this](https://book.pythontips.com/en/latest/context_managers.html).

**Comment by Ev2geny** [comment]
@pietermarsman , I think this is logical to do. I will re-write is with context manager TemporaryFilePath()

**Comment by Ev2geny** [comment]
I have implemented context manager. All tests pass, except the ones on Python 3.4. 
Since support for 3.4 is already decided to be dropped for pdf miner (https://github.com/pdfminer/pdfminer.six/issues/503) I assume I do not have to do anything here

**Review by pietermarsman — APPROVED** [review]

**Comment by pietermarsman** [comment]
Yep, lets wait for #503. The error is caused because prefix and suffix are directly added to the filename. I guess the default values are different in python 3.4 (e.g. empty string).

**Comment by pietermarsman** [comment]
I removed python 3.4 from the following release. Could you rebase on develop and force push?

**Comment by Ev2geny** [comment]
> I removed python 3.4 from the following release. Could you rebase on develop and force push?

@pietermarsman , this is done

**Comment by Ev2geny** [comment]
> I removed python 3.4 from the following release. Could you rebase on develop and force push?
@pietermarsman , this is done now

**Comment by pietermarsman** [comment]
Thanks!

**Pull request merged**
