### PR TITLE
Fix comparations for image colorspace literals

### PR DESCRIPTION
**Pull request by bashkirtsevich**
See issue #131 
Python: 3.6.3

### CODE REVIEW

**Comment by pietermarsman** [comment]
Hi @bashkirtsevich, thanks for your contribution. This is a very late response...

We don't have any test that run this code so I am not sure if this breaks any other kind of pdfs. I can imagine that sometimes the colorspace is a list and sometimes it is not. Do you have any idea if that is the case?

If you want this to be merged you should also add a a test. That makes sure that this code can actually be run (which I believe by looking at it) and it will make sure that we don't change it without thinking. 

Do you have time to work on this?

**Comment by bashkirtsevich** [comment]
In my PR I just fix logical mistakes such as `is` and `in`. 
We using this library with my patch, and its finally work. 
Merge not necessary. May be this PR can helpful as knowledge base.

**Comment by pietermarsman** [comment]
I've just checked if any of our current tests is using the `ImageWriter`, and this is not the case. 

But we do have some sample pdf's that contain images. This is the result of evaluating `image.colorspace` at the start of `ImageWriter.export_image()`.

`nonfree/dmca.pdf`.

- `[/'Indexed', /'DeviceRGB', 255, <PDFObjRef:86>]`

`nonfree/175.pdf`

- `[/'DeviceRGB']`
- `[/'DeviceRGB']`

Both pdfs have a list of colorspaces instead of a single value. And thus checking e.g. `image.colorspace is LITERAL_DEVICE_RGB` is wrong.

**Comment by pietermarsman** [comment]
I've checked the code from this PR with `nonfree/dmca.pdf` and it improves the output! With this PR the code detects that it is a RGB image and should be written to disk as a `.bmp`. With the old code the image is not recognized as RGB and it is written as a generic `.img` file that cannot be easily opened.

**Comment by chengmengli06** [comment]
@pietermarsman I have an pdf with some images write as general ".img" files, how could I convert these images to jpg format?

**Comment by pietermarsman** [comment]
pdfminer.six writes to a .img file if it cannot infer the type of the image. It supports jpeg (.jpg), jbig2 (.jb2) and grayscale (.bmp) images. The bytes of an unrecognized images type are written to this extention: `'.%d.%dx%d.img' % (image.bits, width, height)`. From the filename you can infer the number bits, width and height of the image. I don't know how you should open it.

Please share if you find a way to open the images. Perhaps we can add it to pdfminer.six.

**Pull request merged**
