### PR TITLE
Drop support for legacy Python 2

### LINKED ISSUE #194: Drop python 2 support
https://python3statement.org

### PR DESCRIPTION
**Pull request by hugovk**
* Fixes #194.
* Replaces and closes #301.

### CODE REVIEW

**Comment by pietermarsman** [comment]
I've found [this](https://github.com/pdfminer/pdfminer.six/blob/5558800b970def2812c23b6f8c3b53c2f71fa9eb/pdfminer/high_level.py#L19) reference to python 2. I have no idea what the argument is for. 

The argument `_py2_no_more_posargs` is also mentioned in 3 other place.

**Comment by hugovk** [comment]
Removing that would change the API, what do you suggest?

**Comment by pietermarsman** [comment]
Once python2 is removed it does not serve a function anymore. (I guess, because I do not really know what its function is anyway). So we should remove it at some point. 

Also, I am not seeing anyone actually using it on [github](https://github.com/search?q=_py2_no_more_posargs&type=Code).

I've created issue #324 for deprecating it in the next release (in 2 weeks or so). So lets remove it.

**Comment by pietermarsman** [comment]
I've recreated this PR in #346 so I can rebase.

**Pull request closed without merging**
