### PR TITLE
Charmap build automation

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by pietermarsman** [comment]
This PR mixes the solution for multiple seperate issues. Could you seperate your changes by subject. For example:

- one PR for setup.cfg (already exists, so you can remove the changes for setup.cfg from this PR)
- lzma compression (also in another pr, but remove the setup.cfg from that an remove lzma compression from this commit)
- build charmaps on install or release (that's what this commit is about)
- you so mentioned the use of pickle files in your issue (create a seperate PR for that)

**Comment by KOLANICH** [comment]
>Could you seperate your changes by subject

I can, but the cost of it is merge conflicts because of interdependence.

**Comment by pietermarsman** [comment]
Than I recommend you doing that. It makes reviewing much easier. I think it is easiest if you close this one and cherrypick the commits you want to have in other branches. 

The submodule with the adobe charmaps seems useful to! This also deserves its own issue + PR.

**Comment by pietermarsman** [comment]
Could you merge this PR with #115 since they are related.

**Comment by KOLANICH** [comment]
It was initially done this way, but you have asked me to split them. I am not sure that I can understand the way you like them to be grouped. Feel free to pull the code from my repo, rebase the changes the way you like and create separate PRs.

**Comment by pietermarsman** [comment]
I think you are referring to [this](https://github.com/pdfminer/pdfminer.six/pull/117#issuecomment-511231208) comment:

> This PR mixes the solution for multiple seperate issues. Could you seperate your changes by subject. For example:
> 
> * one PR for setup.cfg (already exists, so you can remove the changes for setup.cfg from this PR)
> * lzma compression (also in another pr, but remove the setup.cfg from that an remove lzma compression from this commit)
> * build charmaps on install or release (that's what this commit is about)
> * you so mentioned the use of pickle files in your issue (create a seperate PR for that)

Sorry if I've confused things. This PR contains build automation and the charmaps as `pickle.gz` files. The other PR uses `lzma` compression and needs the `pickle.gz` files to work. I expected that you would move the `lzma` compression and the `pickle.gz` files work to one PR (since they are related). And the build automation to a separate PR (since I think it is unrelated). 

Anyway, I expect a PR to be a solution for a single specific problem. If that is or was the case and I am wrong, please don't hesitate to say anything about it.

**Comment by pietermarsman** [comment]
I'm closing this PR since I think that generating the charmaps is only useful if they change often, but they don't.

**Comment by KOLANICH** [comment]
>I'm closing this PR since I think that generating the charmaps is only useful if they change often, but they don't.

generating charmaps is needed because I personally don't trust pickles in source code. I guess (based on my experience) using cbor/bson/json will probably be slower than pickles, but at least it is more trustworthy. pickles for me are equivalent to malware because they are essentially source code in an unreadable form.

**Comment by pietermarsman** [comment]
Hi @kolanich, I understand that you are unhappy about closing this PR. If you want to prevent this in the future, make sure that you properly explain the issue and solution. This PR has no description and it is hard for me to guess (from the code) what you want. 

The security issue you are raising might be valid. If this is important to you create a github issue and explain properly what is wrong.

**Pull request closed without merging**
