### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by pietermarsman** [comment]
Whats the difference with #113?

**Comment by KOLANICH** [comment]
>Whats the difference with #113?

Removed everything related to generation of cmaps. And removed explicit parsing - setup() does it itself.

The problem of `setup.py` is that it is executable code of arbitrary structure. setup.cfg is a metadata file, not code. So putting metadata into a separate file with rigid structure is beneficial. Both for automated tools and humans. Though, as I have said, neither GitHub, nor `bandit`, nor `dependencies.io` have support for these files, even though the parser for its format is readily available. Though they don't have support to `setup.py` too, because in order to extract data from setup.py one has to execute it, and it is a security issue. Of course some heuristics using `ast.parse` is possible, but IMHO makes no sense.

**Comment by pietermarsman** [comment]
I'm not really sure why we should do it if there is no real benefit. 

Reasons not to do it:
- might not work on python2 ([SO](https://stackoverflow.com/questions/27077355/how-to-use-setup-cfg-instead-of-setup-py-with-python-2-7))
- I think more people are familiar with `setup.py` that there are with `setup.cfg`. Might be wrong on this.
- might introduce new errors, like the shebang that is hardcoded for python3

I might be a bit conservative here, but I don't see the point of changing nicely formatted working code if there is also weirdly formatted broken code in the rest of the repo. Lets focus on that first and close this PR.

**Comment by KOLANICH** [comment]
>might not work on python2 (SO)

he had used distutil

>I think more people are familiar with setup.py that there are with setup.cfg

familiarity is not needed, the format is trivial and intuitively undestandable. It mirrors setup args.

>might introduce new errors, like the shebang that is hardcoded for python3

isn't shebang a comment, so when called by python 2, it is 8gnored.

**Comment by KOLANICH** [comment]
Any progress merging this?

**Comment by pietermarsman** [comment]
I suggest we not merge this PR and close it since it does not solve any problem (as far as I can see).

@KOLANICH, please make sure in the future that you open an issue to discuss a bug/problem/enhancement/feature before creating a PR.

**Comment by pietermarsman** [comment]
I'm closing this because I don't see the need of using a setup.cfg. 

Also apparently it was a mandatory file earlier, [but not anymore](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/#setup-cfg).

**Comment by KOLANICH** [comment]
>I don't see the need*

is a bulletproof argument.

**Pull request closed without merging**
