### PR TITLE
Fix from-source and Python 3.12 build by removing hard-coded version (#922)

### PR DESCRIPTION
**Pull request by dhdaines**
Switch to using [setuptools-git-versioning](https://github.com/dolfinus/setuptools-git-versioning) instead of a hardcoding the version at release time with a default version string that was not friendly to PEP440, Python 3.12, or building from git source.

**Checklist**

- [ x ] I have read [CONTRIBUTING.md](../CONTRIBUTING.md). 
- [ x ] I have added a concise human-readable description of the change to [CHANGELOG.md](../CHANGELOG.md).
- [ x ] I have tested that this fix is effective or that this feature works.
- [ x ] I have added docstrings to newly created methods and classes.
- [ x ] I have updated the [README.md](../README.md) and the [readthedocs](../docs/source) documentation. Or verified that this is not necessary.

### CODE REVIEW

**Comment by dhdaines** [comment]
not sure why it doesn't get mentioned there but this fixes #922

**Review by pietermarsman — CHANGES_REQUESTED** [review]
This is looking great. I've rewritten the CHANGELOG.md a bit, and merged master into this branch. 

Can you look at the failing tests? If that is fixed it is ready to be merged.

**Comment by pietermarsman** [comment]
@dhdaines I've fixed the tests. Perhaps you can give it another look next week. I'm planning to merge it next week.

**Review by pietermarsman — APPROVED** [review]

**Comment by dhdaines** [comment]
> @dhdaines I've fixed the tests. Perhaps you can give it another look next week. I'm planning to merge it next week.

Hi! Sorry for the late reply... I was on top of a mountain for a few days.  Seems to all work quite well for me on Python 3.12.

As far as I can tell the release workflow should work in the same way but I wouldn't be able to test that :)

**Comment by pietermarsman** [comment]
No worries. I haven't responded in quite a while, and I was not on a mountain :smile: 

The work you put in here is much appreciated!

**Pull request merged**
