### PR TITLE
Fix regression in page layout that sometimes returned text lines out of order

### PR DESCRIPTION
**Pull request by 0xabu**
This fixes issue #658: a regression in text line layout (LTLayoutContainer.group_textboxes) that caused it to merge lines of text into text boxes out of order, by merging two lines as adjacent elements even when there was a third line in between the two.

PR #315 changed the first element of each distance tuple from an int 0 or 1, where 0 was used for initial entries and 1 for subsequently-added groups, to a bool `is_first` where True was used for initial entries. This change broke the desired sort order, because 0 < 1 but True > False, and that was fixed by the followup commit https://github.com/pdfminer/pdfminer.six/commit/2bee7d8dcfd536a88c690a0cd74b0e2dae1947ef inverting the meaning of the bool, but that commit missed adding a `not` where the bool (now correctly called `skip_isany`) was used in an if expression. The fix is just to add that `not`.

### CODE REVIEW

**Comment by 0xabu** [comment]
@pietermarsman @mikkkee take a look, please.

**Review by jstockwin — CHANGES_REQUESTED** [review]
This LGTM, and thanks for the detailed description of the change - very helpful!

One small change needed before this will get merged:
Could you add an entry to the `CHANGELOG.md` to reflect your fix?

**Review by jstockwin — APPROVED** [review]
LGTM

**Comment by 0xabu** [comment]
The py36 build failure here is definitely not the fault of this PR. Comparing https://github.com/pdfminer/pdfminer.six/runs/3846904701 (successful build) and https://github.com/pdfminer/pdfminer.six/pull/659/checks?check_run_id=3847247616 (unsuccessful build) there seem to be different versions of Python 3.6 and pip being fetched, which in turn causes cryptography to try to build Rust code.

**Review by pietermarsman — APPROVED** [review]

**Comment by pietermarsman** [comment]
Thanks again!

**Pull request merged**
