### PR TITLE
Fix TypeError: cannot unpack non-iterable PDFObjRef object, when unpacking the value of 'DW2'

### PR DESCRIPTION
**Pull request by EucliTs0**
An error is occured when the 'DW2' key contains a PDFObjRef object instead of a list of int values, e.g: 'DW2': <PDFObjRef:152>.
To solve this issue, we utilise the resolve1() function

See: https://github.com/pdfminer/pdfminer.six/issues/518

**Pull request**

Thanks for improving pdfminer.six! Please include the following information to
help us discuss and merge this PR:

- A description of why this PR is needed. What does it fix? What does it 
  improve?
- A summary of the things that this PR changes.
- Reference the issues that this PR fixes (use the fixes #(issue nr) syntax). 
  If this PR does not fix any issue, create the issue first and mention that 
  you are willing to work on it.

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide 
instructions so we can reproduce. Include an example pdf if you have one. 

**Checklist**

- [ ] I have added tests that prove my fix is effective or that my feature 
  works
- [ ] I have added docstrings to newly created methods and classes
- [ ] I have optimized the code at least one time after creating the initial 
  version
- [x] I have updated the [README.md](../README.md) or I am verified that this
  is not necessary
- [x] I have updated the [readthedocs](../docs/source) documentation or I 
  verified that this is not necessary
- [x] I have added a consice human-readable description of the change to 
  [CHANGELOG.md](../CHANGELOG.md)

### CODE REVIEW

**Comment by pietermarsman** [comment]
Thanks! Could you go over the checklist? E.g. add a line to the changleog.

**Comment by EucliTs0** [comment]
> Thanks! Could you go over the checklist? E.g. add a line to the changleog.

Sure, done!

**Comment by pietermarsman** [comment]
Assuming the cicd error will be fixed because I reverted the change that caused the error https://github.com/pdfminer/pdfminer.six/pull/534

**Comment by pietermarsman** [comment]
@EucliTs0 Thanks!

**Pull request merged**
