### PR TITLE
use six.iteritems instead of dict.iteritems

### PR DESCRIPTION
**Pull request by yosida95**
It was deleted in Python 3.

This PR also includes a little bit of PEP 8 work.

### CODE REVIEW

**Comment by yosida95** [comment]
resolved conflicts

**Comment by RolandColored** [comment]
Why can't we just use dict.items?

**Comment by yosida95** [comment]
I just replaced use of `dict.iteritems` in the original code with `six.iteritems` because I don't know whether there is any reason to use `dict.iteritems`. It seems it's fine to replace with `dict.items` to me, but there might be some memory usage and/or performance regression in Python 2 because `dict.items` allocates memory at once instead of using generator.

**Comment by pietermarsman** [comment]
What issue does this solve?

If not any, let's close this.

**Comment by pietermarsman** [comment]
I suggest we close this since it has an (active) duplicate in #274 .

**Comment by pietermarsman** [comment]
This PR can be closed since another PR (#274) solved this.

**Comment by yosida95** [comment]
I agree that this PR with one-year aged approval review can be closed because of duplicate #274 created just 10 days ago. It seems @pietermarsman understands the two PRs intend to solve the same issue and has a strong reason to merge #274 in favor of #123.

**Comment by pietermarsman** [comment]
Wow, yes, in hindsight is seems a little strange that we merged the other PR. I guess I just saw that one earlier and considered this to be the "duplicate". Next time I will try to check for duplicates earlier. 

Anyway, glad we solved this problem :)

**Pull request closed without merging**
