### PR TITLE
utils.py: Fixing assertion in drange to allow equal inputs

### PR DESCRIPTION
**Pull request by abhmul**
We should allow `drange` to allow the same input value for `v0` and `v1`. In this case, `drange` will return an iterator of one element: `v0 // d`.

I ran into an issue when using [Camelot](https://github.com/socialcopsdev/camelot), where the values passed into `v0` and `v1` were the same. The original assertion in `drange` will fail when values for `v0` and `v1` are the same. However, I don't see why they can't be the same. In this case, `drange` will return a `range` iterator with just a single element equal to `v0 // d`. Making this change fixed the assertion without any incorrect change in the output of my code.

I am not very familiar with the codebases of `pdfminer` or `Camelot`, so I'd like an active contributor to take a look and see if there are any obvious issues. In the meanwhile, I'll continue to do some more investigation to see if this change could pose a problem somewhere, and I'll update this PR with anything I find.

### CODE REVIEW

**Comment by pietermarsman** [comment]
This change would make the interface of `drange` different from the interface of the built-in `range`. 

`
>>> list(range(0, 0))
[]
`

This would be confusing since `drange` is obviously modelled after `range.

**Comment by pietermarsman** [comment]
Hi @abhmul, your PR seems to be related to #66. Do you have time to work on this?

**Comment by abhmul** [comment]
Sure, I can do it this week, should be a quick fix.

**Comment by pietermarsman** [comment]
I've checked and there is no `except` clause in pdfminer that catches a `AssertionError`. Thus the assertion can safely be replaced by returning an empty list like `range` does.

**Pull request merged**
