### PR TITLE
decode cid: 160 and 173 to spaces

### PR DESCRIPTION
**Pull request by h2ri**

### CODE REVIEW

**Comment by RolandColored** [comment]
Looks good, although the title contains a typo (170 instead of 173)

**Comment by h2ri** [comment]
@RolandColored Thank you for the update, fixed the typo. Could u please merge the updates?

**Comment by h2ri** [comment]
@goulu Would u be able to merge these changes?

**Comment by Naddiseo** [comment]
Isn't [charcode 173 a "soft hyphon"](http://www.fileformat.info/info/unicode/char/00AD/index.htm)?

We have some PDFs that display using the hyphon, and used to return `"(cid:173)"` in pdfminer, now they return spaces.

**Pull request merged**
