### PR TITLE
Fix #800

### LINKED ISSUE #800: Follow up from pull request #744
Hi Is it possible to add as a requirement of any changes to the install requirements that they all be non copy left packages with no copy left dependencies as if any were this would mean that pdfminer.six would be copy left itself rather than MIT

### PR DESCRIPTION
**Pull request by pettzilla1**
**Pull request**

Adds additional requirements to the CONTRIBUTING.md file.

Closes #800 

**How Has This Been Tested?**

Using [licensecheck](https://pypi.org/project/licensecheck/)

**Checklist**

- [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md). 
- [x] I have added a concise human-readable description of the change to [CHANGELOG.md](../CHANGELOG.md).
- [x] I have tested that this fix is effective or that this feature works.
- [x] I have added docstrings to newly created methods and classes.
- [x] I have updated the [README.md](../README.md) and the [readthedocs](../docs/source) documentation. Or verified that this is not necessary.

### CODE REVIEW

**Comment by KunalGehlot** [comment]
Mentioning #800 to link the issue

**Comment by pettzilla1** [comment]
Hi @KunalGehlot , I checked the current requirements a while ago and there hasn't been an update since.
To do what is mentioned you have to look at what packages are required for the install of a package this is ether in the setup file or can be in a separate file  they reference . if those packages are on github the licence tag should tell you there licence and the process again followed for their dependencies.  pypi can also be used to get some of this information

**Comment by pettzilla1** [comment]
@pietermarsman are you able to review and merge ?

**Comment by pettzilla1** [comment]
@pietermarsman  , do you have any issues with this , if not please could it be merged ?

**Comment by pietermarsman** [comment]
I checked our current licenses with [licensecheck](https://pypi.org/project/licensecheck/)  and they are all compatible. 

Ideally we want it in cicd, but I did not get that to work just yet. I've created an [issue](https://github.com/pdfminer/pdfminer.six/issues/930) for that.

**Comment by pietermarsman** [comment]
Thanks @pettzilla1 for starting this!

**Pull request merged**
