### PR TITLE
Fix ordering of textlines within a textbox when boxes_flow is disabled

### LINKED ISSUE #411: Disabling boxes flow makes lines be in wrong order within text boxes
**Bug report**

When passing `boxes_flow` as `None`, we don't run the full advanced layout analysis, but rather the order of text boxes will depend on their position on the page only. This is intentional.

If we were passing boxes flow, we'd group the text boxes and then call `analyze` on each group ([here](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/layout.py#L811)). This filters down so that `analyze` is called on the text boxes themselves. When `boxes_flow=None`, we don't call `analyze` on the text boxes, which results in the lines coming in the wrong order as they don't get sorted.

Note that `boxes_flow` is not used in the `analyze` method of text boxes, it is only used for groups of text boxes (which we never have if boxes flow is disabled).

To fix this, we just need to make sure that `analyze` is always called on the text boxes, even if we don't group them.

[Example PDF](https://www.dropbox.com/s/jjhlbsynrnjuq6i/negative_line_margin_example.pdf?dl=0)

Example code:
```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LAParams

la_params = LAParams(boxes_flow=None)

for page in extract_pages("example.pdf", laparams=la_params, caching=False):
    print("*****OUTPUT:*****")
    for element in page:
        print(element)
```

Example output:
```
*****OUTPUT:*****
<LTTextBoxHorizontal(-1) 58.100,343.402,106.178,406.702 'Text 3Text 2Text 1'>
```

Expected output:
```
*****OUTPUT:*****
<LTTextBoxHorizontal(-1) 58.100,343.402,106.178,406.702 'Text 1\nText 2\nText 3\n'>
```

### PR DESCRIPTION
**Pull request by jstockwin**
**Pull request**

Closes #411

Note: It does work to add the `analyze` call inside the `get_key` function, but that felt a bit strange since it has nothing to do with getting the key, therefore I decided to do it outside of this.

**How Has This Been Tested?**

[Example PDF](https://www.dropbox.com/s/jjhlbsynrnjuq6i/negative_line_margin_example.pdf?dl=0)

Example code:
```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LAParams

la_params = LAParams(boxes_flow=None)

for page in extract_pages("example.pdf", laparams=la_params, caching=False):
    print("*****OUTPUT:*****")
    for element in page:
        print(element)
```

Before fix:
```
*****OUTPUT:*****
<LTTextBoxHorizontal(-1) 58.100,343.402,106.178,406.702 'Text 3Text 2Text 1'>
```

After fix:
```
*****OUTPUT:*****
<LTTextBoxHorizontal(-1) 58.100,343.402,106.178,406.702 'Text 1\nText 2\nText 3\n'>
```

**Checklist**

- [x] I have added tests that prove my fix is effective or that my feature 
  works  -> Actually the tests I added for without boxes flow kind of show the issue, you can see the output changes (less `\n`). The output is now consistent.
- [X] I have added docstrings to newly created methods and classes
- [X] I have optimized the code at least one time after creating the initial 
  version
- [X] I have updated the [README.md](../README.md) or I am verified that this
  is not necessary
- [X] I have updated the [readthedocs](../docs/source) documentation or I 
  verified that this is not necessary
- [X] I have added a consice human-readable description of the change to 
  [CHANGELOG.md](../CHANGELOG.md)

### CODE REVIEW

**Comment by jstockwin** [comment]
Not sure why the tests still say pending... Travis is green: https://travis-ci.org/github/pdfminer/pdfminer.six/builds/671715428

I actually had this issue on a different project the other day...

**Comment by jstockwin** [comment]
@pietermarsman Cool, I've added my test PDF, and added some tests for when boxes flow is disabled. I also threw in some bonus tests for the line margin parameter, since I know the line margin is 0.2 in this case.

I'll try and get round to adding some more tests, but probably not part of this PR.

**Comment by jstockwin** [comment]
Travis didn't build for my new commit... not sure how to fix that

**Comment by jstockwin** [comment]
@pietermarsman I have just rebased to resolve conflicts in the changelog, and Travis has now done its job. Any chance this can get merged?

**Comment by pietermarsman** [comment]
Thanks @jstockwin! 

(Sorry for the delay)

**Pull request merged**
