### PR TITLE
Improved architecture of cmap converter to make it usable from setup.py

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by pietermarsman** [comment]
What is the difference with #116?

**Comment by KOLANICH** [comment]
setup.py alone without any calling makefiles should generate working wheels.

**Comment by pietermarsman** [comment]
I am sorry but I don't understand you. Could you be more explicit in what you want to achieve. 

If you want to change anything on the build and release process you should chat first with @ganeshtata. He is the one did the lastest release and knows what can/should/must be improved and what not.

**Comment by KOLANICH** [comment]
Any progress merging this?

**Comment by pietermarsman** [comment]
I suggest we *not* merge this PR and close it since it does not solve any problem (as far as I can see). 

@KOLANICH, please make sure in the future that you open an issue to discuss a bug/problem/enhancement/feature before creating a PR.

**Pull request closed without merging**
