### PR TITLE
Send color to XML conversion

### PR DESCRIPTION
**Pull request by pquentin**
The change can be tested with the following snippet:

```
import contextlib
import io
import sys

from pdfminer.converter import XMLConverter
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.layout import LAParams


with open(sys.argv[1], 'rb') as in_fp:
    out_fp = io.BytesIO()
    rsc_mgr = PDFResourceManager(caching=True)
    laparams = LAParams()
    converter = XMLConverter(rsc_mgr, out_fp, codec='UTF-8', laparams=laparams)

    with contextlib.closing(converter) as device:
        interpreter = PDFPageInterpreter(rsc_mgr, device)
        for page in PDFPage.get_pages(in_fp):
            interpreter.process_page(page)

    print(out_fp.getvalue().decode('UTF-8'))
```

### CODE REVIEW

**Comment by pquentin** [comment]
Python 2.6 is no longer supported. It would make your lives easier if you simply dropped support here too! https://snarky.ca/stop-using-python-2-6/

**Comment by ganeshtata** [comment]
@pquentin Dropped python 2.6 check.

**Comment by pquentin** [comment]
Thanks @ganeshtata!

**Comment by OisinMoran** [comment]
Do you have an example PDF where this gets the colour of the text? All I can seem to get is `ncolor=None` or `ncolor=0` (which I assumed could be interpreted as black, however there were multiple other font colours present).

**Comment by pquentin** [comment]
@OisinMoran I've only used this work to retrieve levels of gray. I use the name "color" because this is what was used in pdfminer, but I don't know enough about PDFs to tell you more, sorry.

**Pull request merged**
