### PR TITLE
Bug: _is_binary_stream should recognize TextIOWrapper as non-binary, escaped \r\n should be removed

### LINKED ISSUE #615: TextIOWrapper mistakenly classified as binary
**Bug report**

Bug is in converter.PDFConverter._is_binary_stream

I have only just caught up with pdfminer.six, was using pdfminer.20191103
This allowed me to use a TextIOWrapper as the output stream for a TextConverter, but this fails with pdfminer.six because `_is_binary_stream` fails to recognise TextIOWrapper as non-binary.

- Steps to reproduce the bug.
```
        text_io = TextIOWrapper(BytesIO())
        rsrcmgr = PDFResourceManager(caching=True)
        converter = TextConverter(rsrcmgr, text_io,
                                  laparams=LAParams(), imagewriter=None)
        interpreter = PDFPageInterpreter(rsrcmgr, converter)
        ...
       for page in PDFPage.get_pages(...):
            # Read page contents
            interpreter.process_page(page)
```

- If relevant, include the output and/or error stacktrace. 
```
  ...
    render(ltpage)
  ...
  File "/usr/lib/python3.6/site-packages/pdfminer/converter.py", line 211, in render
    self.write_text(item.get_text())
  File "/usr/lib/python3.6/site-packages/pdfminer/converter.py", line 202, in write_text
    self.outfp.write(text)
TypeError: write() argument must be str, not bytes
```

The fix is trivial, see pull request shortly...

### LINKED ISSUE #624: Escaped EOL in String not being removed correctly when it's \r\n
PDF spec [1] says that an escaped EOL in a String should be removed, but when it's a two-character EOL on the \r is removed, leaving the \n.

To reproduce, first observe that the hover text for the link in the attached is, correctly, "http://example.org/test?arg=value".

Then, run the following from the command line:
`.../tools/pdf2txt.py -p 0 -t tag -d EscapedEOL.pdf 2>&1 >/dev/null | less`
Search for 'arg=' and you'll see the following:
`DEBUG:pdfminer.psparser:nexttoken: (2103, b'http://example.org/test?arg=va\nlue')`
That \n shouldn't be there.
[EscapedEOL.pdf](https://github.com/pdfminer/pdfminer.six/files/6555667/EscapedEOL.pdf)

### PR DESCRIPTION
**Pull request by htInEdin**
**Pull request**

I have only just caught up with pdfminer.six, was using pdfminer.20191103

Two bug fixes:

pdfminer.20191103 allowed me to use a TextIOWrapper as the output stream for a TextConverter, but this fails with pdfminer.six because  _is_binary_stream fails to recognise TextIOWrapper as non-binary.

All that's needed is to test for instances of io.TextIOBase

Fixes #615.

Also, fixed a bug in psparser which failed to remove all of an escaped \r\n.

Fixes #624.

**How Has This Been Tested?**

I have a link extractor ([patched version of pdfx](https://github.com/htInEdin/pdfx/commit/66533d1574becd72e0744deceb019e070e126d01)) which ran on a 200 page pdf, finding 1300+ links, using pdfminer.20191103, crashed with pdfminer.20201018, runs again with the same output as before when patched with these changes.  Running on a sample of 900+ pdf files from Common Crawl of August 2019, it finds more and cleaner links that when using pdfminer.20191103.

**Checklist**

- [x]  I have added tests that prove my fix is effective or that my feature  works
- [x]  I have added docstrings to newly created methods and classes
- [x]  I have optimized the code at least one time after creating the initial version
- [ ]  I have updated the README.md or I am verified that this is not necessary
- [ ]  I have updated the readthedocs documentation or verified that this is not necessary
- [x]  Commit includes a ChangeLog, I don't understand the new format, sorry, but have supplied an old-format version

### CODE REVIEW

**Comment by pietermarsman** [comment]
@htInEdin I did some changes to make it more readable. Could you double-check the psparser.py logic for literal strings? I find that these kinds of things are very easy to get wrong.

**Comment by htInEdin** [comment]
Pieter Marsman writes:

> @htInEdin<https://github.com/htInEdin> I did some changes to make it
> more readable. Could you double-check the psparser.py logic for
> literal strings? I find that these kinds of things are very easy to
> get wrong.

Thanks, will do, on holiday but back next week.

ht
-- 
       Henry S. Thompson, School of Informatics, University of Edinburgh
      10 Crichton Street, Edinburgh EH8 9AB, SCOTLAND -- (44) 131 650-4440
                Fax: (44) 131 650-4587, e-mail: ***@***.***
                       URL: http://www.ltg.ed.ac.uk/~ht/
 [mail from me _always_ has a .sig like this -- mail without it is forged spam]

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by pietermarsman** [comment]
@htInEdin bump ;) 

(Just a friendly reminder, no hurry)

**Comment by htInEdin** [comment]
I've reviewed your work above, thanks, and _parse_string(_1) in particular, and I think it's good to go.

**Comment by htInEdin** [comment]
Pieter Marsman writes:

> @htInEdin<https://github.com/htInEdin> bump ;)
>
> (Just a friendly reminder, no hurry)

Done.

ht
-- 
       Henry S. Thompson, School of Informatics, University of Edinburgh
      10 Crichton Street, Edinburgh EH8 9AB, SCOTLAND -- (44) 131 650-4440
                Fax: (44) 131 650-4587, e-mail: ***@***.***
                       URL: http://www.ltg.ed.ac.uk/~ht/
 [mail from me _always_ has a .sig like this -- mail without it is forged spam]

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by htInEdin** [comment]
Bother, I still haven't quite gotten the hang of branch management.  The above 4 commits were meant to be for a new 'preferLoggingToWarning' pull request, now merged into this one :-(.
d6fc079 is the correct commit to pull from for this request.  Let me know if I need to do some surgery...

**Review by pietermarsman — APPROVED** [review]

**Comment by pietermarsman** [comment]
@htInEdin I think I fixed it by reverting them. 

Merged it now. Thanks for the work!

**Pull request merged**
