### PR TITLE
Issue #720 PDFObjRef

### PR DESCRIPTION
**Pull request by gosiafilipek**
PDFObjRef insted of int/float.
Error description in issue #720 #772

### CODE REVIEW

**Comment by Pilli68** [comment]
Hello everyone , I am new to Github. So I need your help/suggestions/inputs/advice.
Here I attached my pdf file. i want to convert each and everything in pdf into text without header data .footer data. Kindly request you please do needful action. 
Note: Pdf file contains mathematical equations , images ,logos  and other stuff. 


[Unit-1.pdf](https://github.com/pdfminer/pdfminer.six/files/9016378/Unit-1.pdf)

**Comment by pietermarsman** [comment]
Closing in favor of #772. 

Let me know if I misunderstood something.

**Comment by gosiafilipek** [comment]
@pietermarsman 
I found another place with this error.
#772 solved only part of problem.

**Comment by pietermarsman** [comment]
@gosiafilipek Can you create an new issue that details the problem? The issue in #720 is fixed by #772.

**Pull request closed without merging**
