### PR TITLE
use lzw module logger, not the root

### PR DESCRIPTION
**Pull request by sivikt**

### CODE REVIEW

**Comment by pietermarsman** [comment]
@sivikt do you have time to work on this?

**Comment by sivikt** [comment]
Yes, I can do it

**Comment by pietermarsman** [comment]
@sivikt, I think something went wrong. The changes are committed to a branch on your fork of the repository and not to this PR. If you commit to your master branch than the changes will appear in this PR.

**Comment by sivikt** [comment]
Thank you.

**Pull request merged**
