### PR TITLE
Fix CR/LF, use docstring for package description

### PR DESCRIPTION
**Pull request by bittner**
- Move package description into package docstring
- Convert Windows/DOS line endings CR/LF to Unix LF (again!)

Fixes a regression of PR #58.

### CODE REVIEW

**Comment by vstoykov** [comment]
You can also add Python 3.6 classifier ;)

**Comment by bittner** [comment]
Good point, @vstoykov! I've also updated the project URL, which [currently points to a non-existing GitHub repo](https://pypi.python.org/pypi/pdfminer.six/20170720) (404) on PyPI.

@goulu Can be merged now. Thanks!

**Comment by bittner** [comment]
@goulu Would you mind merging? The changes should be non-critical, hence an easy merge candidate. Thank you.

**Comment by goulu** [comment]
sure ... was on holidays, sorry for the delay ...

**Pull request merged**
