### PR TITLE
#833 PDFObj instead of int

### LINKED ISSUE #833: PDFObjRef  instead of int
I've encountered bug during extracting pages using extract_pages() (pdfminer.high_level). 
I already found a solution so I will create pull request with it.
Image below provides this bug:
image
image
image

pdfminer version: 20221105
pdf to recreate bug: 
[pdf_bug_1.pdf](https://github.com/pdfminer/pdfminer.six/files/10030743/pdf_bug_1.pdf)

### PR DESCRIPTION
**Pull request by gosiafilipek**
resolve1 on elements of self.attr['MediaBox'] in pdfpage
resolve1 on width in pdffont

Closes #833

### CODE REVIEW

**Comment by KunalGehlot** [comment]
Looks like some tests failed. 
Try running `nox` to fix these issues.

**Comment by gosiafilipek** [comment]
@KunalGehlot 
I run nox and pushed changes.
There are still one test failed, but I didn't change that part of code.
image
Do you have any suggestions what can I do to fix it?

**Comment by gosiafilipek** [comment]
> @KunalGehlot I run nox and pushed changes. There are still one test failed, but I didn't change that part of code. image Do you have any suggestions what can I do to fix it?

@pietermarsman @KunalGehlot any advice?

**Comment by pietermarsman** [comment]
Thanks for this fix!

**Comment by paveltyavin** [comment]
This change created a bug:

```TypeError: 'PDFObjRef' object is not iterable```

**Pull request merged**
