### PR TITLE
Add contribution guidelines and refer to it in the readme

### LINKED ISSUE #258: Describe how to behave as a contributor
I think it would help future contributors to participate if it is clear what we expect from them and what they can expect from the project. I'm thinking of the following:

- Use issues to point to problems
    - Discuss possible improvements in an issue
    - Include a minimal reproducible example if possible
    - Include the package version
- Use pull requests to fix problems
    - So no PR without an issue
    - Point your PR to the develop branch
    - PR's should be PEP8 compliant
    - PR's should create or update PEP257 docstrings if necessary. 
    - PR's should include testing of the minimal reproducing examle if possible
    - PR's should work with python2 and python3 (for now)
    - PR's should succesfully run test-suite (on travis)

### PR DESCRIPTION
**Pull request by pietermarsman**
This commit fixes #258.

### CODE REVIEW

**Comment by pombredanne** [comment]
@pietermarsman Looking good !

**Comment by ganeshtata** [comment]
This is awesome! Thank you @pietermarsman !

**Comment by pietermarsman** [comment]
Could you wait just a sec with the merge? I am including a sentence on the value of "problematic pdf's"

**Comment by ganeshtata** [comment]
Sure.

**Comment by pietermarsman** [comment]
Done!

**Pull request merged**
