### PR TITLE
Started using setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
@goulu @ganeshtata Are you going to merge my PRs passing the tests?

**Comment by ganeshtata** [comment]
@KOLANICH  Yes. Will try and merge them.

**Comment by KOLANICH** [comment]
I can, but why to do it, if it works even on ancient pythons?

**Comment by ganeshtata** [comment]
It is just a suggestion, to ensure that in all the new code changes, certain norms are followed. I am not saying its necessary, but its a small change which can be incorporated easily. Thank you.

**Comment by KOLANICH** [comment]
What are the `certain norms`?

**Comment by KOLANICH** [comment]
I have checked, it's really doesn't work on 2.7. Made `os.path`

**Comment by ganeshtata** [comment]
Thank you for the changes. **Certain Norms** just means following common python standards. Why do you have to be so particular about a small thing? It was just a small suggestion.

**Comment by KOLANICH** [comment]
>Certain Norms just means following common python standards

Standards are codified into a document. Like `PEP`s, w3c RFCs, ISO and IEC documents. The things which are not codified are not standards.

**Comment by ganeshtata** [comment]
Okay. So do you want me to cite these "documents"? What do you exactly need?

**Comment by KOLANICH** [comment]
1 If you are satisfied with my PR, then I expect it to be merged.
2 If you wanna codify some requirements, you can create [Contributing.md](https://github.com/blog/1184-contributing-guidelines)

**Comment by KOLANICH** [comment]
ping

**Comment by pietermarsman** [comment]
I don't see the advantage of using a `setup.cfg` compared to just using the `setup.py`. If there is a problem with how it is organized right now please create an issue for that. For now, I think this pr can be closed without merging.

**Comment by KOLANICH** [comment]
>I don't see the advantage of using a setup.cfg

There is no for now: we still execute the code in `setup.py`. Where the metadata should be stored is a opionated decision. IMHO it is better to store it in a separate file of known format which is not meant to contzin any code. It is easier for third-party tools to parse it than to extract the info from python code. Though I don't know any third-party tools using it. Most of third-party tools use only `requirements.txt` currently.

**Comment by pietermarsman** [comment]
> IMHO it is better to store it in a separate file of known format which is not meant to contzin any code.

Ah, I understand that. 

I would suggest that you close this PR and that we focus on the other ones.

**Pull request closed without merging**
