### PR TITLE
Start using GIT LFS for binaries

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by RolandColored** [comment]
Great idea! Unfortunately this doesn't change anything for already committed files, nor does it help to remove and readd the binaries, cause they are saved in the history forever. It's needed to clean the history with a tool like https://rtyley.github.io/bfg-repo-cleaner/

**Comment by pietermarsman** [comment]
I also think this is a great suggestion. This allows testing of much more actual pdf files.

Is this PR all there is to get this to work? Or is there some manual action required?

Does this work on Travis? Like that the pdfs are actually in LFS for this commit?

**Comment by KOLANICH** [comment]
No, manual action is required. We should close this pr and use the s?? software converting repos

**Comment by RolandColored** [comment]
https://rtyley.github.io/bfg-repo-cleaner Can do that pretty well

**Comment by KOLANICH** [comment]
Not quite. I had no success with it in fact. The only tool that had managed to convert a repo successfully was ... `git lfs migrate`.

**Pull request closed without merging**
