### PR TITLE
pep8 correction for few files in /tools/ 328 > 160 to go

### LINKED ISSUE #312: Use code-style enforcement
A lot of files in this project don't follow [PEP8](https://www.python.org/dev/peps/pep-0008/). 

I would like to have some code-style enforcement in this project because (for me) it makes the code more readable and maintainable. 

I've earlier worded with [flake8](https://flake8.readthedocs.io/en/latest/faq.html) and think it works really well. 

Also see this earlier (closed) PR: https://github.com/pdfminer/pdfminer.six/pull/92.

### PR DESCRIPTION
**Pull request by fakabbir**
**Description**

Please include a summary of the change and which issue is fixed. If this does not fix an issue, then first create a new issue. Please also include relevant motivation and context.

Fixes #312 

**How Has This Been Tested?**
`flake8 --count`

**Checklist**

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the [README.md](../README.md) and other documentation, or I am sure that this is not necessary
- [ ] I have added a consice human-readable description of the change to [CHANGELOG.md](../CHANGELOG.md)
- [ ] I have added docstrings to newly created methods and classes
- [x] I have optimized the code at least one time after creating the initial version

### CODE REVIEW

**Comment by fakabbir** [comment]
@pietermarsman Hi, I see some errors with the build. Guess its due to some miss with build config. Can you please have a look ?

**Comment by fakabbir** [comment]
Error Message
```
py36 run-test: commands[0] | flake8 pdfminer/ tools/ tests/ --count --statistics
pdfminer/ascii85.py:50:28: W605 invalid escape sequence '\d'
pdfminer/ascii85.py:51:33: W605 invalid escape sequence '\d'
pdfminer/ascii85.py:51:40: W605 invalid escape sequence '\s'
pdfminer/ascii85.py:51:49: W605 invalid escape sequence '\d'
pdfminer/ascii85.py:51:54: W605 invalid escape sequence '\s'
5     W605 invalid escape sequence '\d'
5
ERROR: InvocationError for command /home/travis/virtualenv/python3.6.7/bin/flake8 pdfminer/ tools/ tests/ --count --statistics (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36: commands failed
The command "tox -r" exited with 1.
Done. Your build exited with 1.
```

**Comment by pietermarsman** [comment]
Hi @fakabbir, 

The build config looks good!

There is a difference in the number of errors that you are reporting (160) and those reported in travis (5). The travis flake8 is limited to the pdfminer/, tools/ and tests/ directories. Perhaps that's the difference?

**Comment by fakabbir** [comment]
Strange, I still can see 5,
image


> Hi @fakabbir,
> 
> The build config looks good!
> 
> There is a difference in the number of errors that you are reporting (160) and those reported in travis (5). The travis flake8 is limited to the pdfminer/, tools/ and tests/ directories. Perhaps that's the difference?

**Comment by fakabbir** [comment]
Maybe if its less than 10, we can merge this to develop and close this branch too. Finally the numbers got smaller :)

**Comment by pietermarsman** [comment]
It was also 5 on the gitlab runner. I've fixed those 5 on de pep8 branch.

The only thing left now is a python 2 error. :unamused:

**Comment by fakabbir** [comment]
> It was also 5 on the gitlab runner. I've fixed those 5 after I've merged this PR on de pep8 branch.
> 
> The only thing left now is a python 2 error. 😒

Aren't we removing support for Python 2 ?

**Pull request merged**
