### PR TITLE
Deprecate Python 3.4 and 3.5

### PR DESCRIPTION
**Pull request by estshorter**
**Pull request**

For issue #503
This code is based on 3fbaa574938e1588da9167ddc913b17f3ff80a40.

**How Has This Been Tested?**

I tested in my environment.

**Checklist**

- [ ] I have added tests that prove my fix is effective or that my feature 
  works
- [ ] I have added docstrings to newly created methods and classes
- [x] I have optimized the code at least one time after creating the initial 
  version
- [x] I have updated the [README.md](../README.md) or I am verified that this
  is not necessary
- [x] I have updated the [readthedocs](../docs/source) documentation or I 
  verified that this is not necessary
- [x] I have added a consice human-readable description of the change to 
  [CHANGELOG.md](../CHANGELOG.md)

### CODE REVIEW

**Comment by Ev2geny** [comment]
Hello, I think also this line needs to be updated
https://github.com/pdfminer/pdfminer.six/blob/f03657e5c48152d4a86a68c680131d5203c8e804/tox.ini#L2

**Comment by estshorter** [comment]
I think tests should be removed after dropping support.

**Comment by flywire** [comment]
Why deprecate Python 3.4 and 3.5? What were the issues?

**Comment by estshorter** [comment]
Did you see https://github.com/pdfminer/pdfminer.six/issues/503 ?
Because it takes effort to support ancient Python (3.5 and earlier).
For example, we cannot use useful syntax like f-string in those versions.

**Comment by flywire** [comment]
OK, suggest add `End of support` comment:  https://www.python.org/downloads/

**Pull request merged**
