### PR TITLE
Add handling of jpx image decoding

### LINKED ISSUE #163: JPXDecode error
Hello, I have a problem with pdf image extraction. When I invoke `stream.get_data()`, library says, that she doesnt supports `JPXDecode` filter (not implemented). How I can avoid or fix this bug? I need image data.

### PR DESCRIPTION
**Pull request by fgregg**
**Pull request**

This PR adds handling for the JPXDecode filter, as suggested in https://github.com/pdfminer/pdfminer.six/issues/163#issuecomment-404343230. This allows extraction of images from pdfs that use this filter

Will fix #163 

**How Has This Been Tested?**

Tested locally. Images extracted correctly. Unfortunately, I do not have non-proprietary pdfs to share.

**Checklist**

- [ ] I have added tests that prove my fix is effective or that my feature 
  works
- [x] I have added docstrings to newly created methods and classes
- [x] I have optimized the code at least one time after creating the initial 
  version
- [x] I have updated the [README.md](../README.md) or I am verified that this
  is not necessary
- [x] I have updated the [readthedocs](../docs/source) documentation or I 
  verified that this is not necessary
- [x] I have added a consice human-readable description of the change to 
  [CHANGELOG.md](../CHANGELOG.md)

### CODE REVIEW

**Comment by jangxyz** [comment]
Any updates on this? Reached to the exact same fix as this PR. Is there any specific reason why this PR is on hold?

**Comment by pietermarsman** [comment]
PIL is used without it being in the requirements. Created #701 for this.

**Comment by pietermarsman** [comment]
Had to merge with command line due to conflict: 708dd20

**Comment by pietermarsman** [comment]
@fgregg thanks for the work. @jangxyz Thanks for the review.

**Pull request closed without merging**
