### PR TITLE
Fix: Broken link to Reitz's "Be Cordial"

### PR DESCRIPTION
**Pull request by goingforbrooke**
Fixed broken hyperlink by updating target to match the new URL format on Kenneth Reitz's website.

**Pull request**

Please *remove* this paragraph and replace it with a description of your PR. Also include the issue that it fixes. 

**How Has This Been Tested?**

Please *remove* this paragraph with a description of how this PR has been tested.

**Checklist**

- [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md). 
- [x] I have added a concise human-readable description of the change to [CHANGELOG.md](../CHANGELOG.md).
- [x] I have tested that this fix is effective or that this feature works.
- [x] I have added docstrings to newly created methods and classes.
- [x] I have updated the [README.md](../README.md) and the [readthedocs](../docs/source) documentation. Or verified that this is not necessary.

### CODE REVIEW

**Comment by goingforbrooke** [comment]
Noted change in `CONTRIBUTING.md`. Ready for merge.

**Comment by goingforbrooke** [comment]
Noted hyperlink fix in `CHANGELOG.md`. Closing to reopen with new commit.

**Comment by goingforbrooke** [comment]
Checklist complete. Ready to merge.

**Comment by pietermarsman** [comment]
@goingforbrooke Thanks for taking the time to fix this!

Merging...

**Pull request merged**
